### PR TITLE
Generate differents profile in pom file, Manifest Version update and New MOJO bwbackupEAR

### PR DESCRIPTION
**Pull request by Tantino**
I like to contribute in this plugin. For my project I need generate the pom file with different profiles foreach test enviroment.
Thanks and Regards.

```
modified:   
```

bw6.studio.maven.plugin/src/com/tibco/bw/studio/maven/modules/BWDeploymentInfo.java
    modified:   bw6.studio.maven.plugin/src/com/tibco/bw/studio/maven/pom/builders/AbstractPOMBuilder.java
    modified:   bw6.studio.maven.plugin/src/com/tibco/bw/studio/maven/pom/builders/ApplicationPOMBuilder.java
    modified:   bw6.studio.maven.plugin/src/com/tibco/bw/studio/maven/wizard/WizardPageEnterprise.java

New functionality Manifest Version update with maven version.
New command for backup .EAR and Profile application.

`mvn bwbackupEAR`

### CODE REVIEW

**Comment by Tantino** [comment]
I like to contribute in this plugin. For my project I need generate the pom file with different profiles foreach test enviroment.
Thanks and Regards.

**Comment by Tantino** [comment]
Update MANIFEST File with maven version.
New funcionality for backup aplication and profile.

`mvn bwbackupEAR`

**Comment by RajibBiswasTibco** [comment]
Hi Tantino,
I like the idea of backing up ear and profile, which will be helpful in CI. But it should be part of the same EAR Installer Mojo, and there should be a option of selecting whether user wants to backup the ear or not. And if user wants to backup ear, then user should also provide the backup location, because if you keep it inside 'target' folder, then mvn clean will delete all backup ears.

**Comment by Tantino** [comment]
Hi @RajibBiswasTibco ,
"What are we trying to achieve here in the ManifestWriter ?" In my project we use this command maven:
`mvn versions:set -DnewVersion=1.0.1` . 
This command replace the version value in pom file. When you deploy the application in bwagents always have the same version 1.0.
tibco enterprise administrator - google chrome_8

I think that tibco have the issue in this case because the version is not version-bundle if not manifest-version.

Thanks and regards.

**Comment by RajibBiswasTibco** [comment]
All these changes has been merged into the master branch. Closing this pull request.

**Pull request closed without merging**
