### PR TITLE
Updated mvn-driven OSGI versioning with mvn bw module dependency management fork

### PR DESCRIPTION
**Pull request by tcosley**
I started with the latest master branch version and hand-merged in my changes to enable maven pom versioning to drive OSGI version in the BW modules..

This version of the plugin also uses maven to resolve BW module (shared or app) dependencies when building an EAR (rather than relying on relative/workspace resolution).

There is also an earUrl override paramater added for the BW deployment feature.

Finally there is a Sample folder that illustrates how to setup poms to use this plugin version.

### CODE REVIEW

**Comment by rajani007** [comment]
Hi,
Can you please build this plugin and check it in? Or provide steps how build it in my local?

**Comment by awagle** [comment]
@rajani007 stay tuned, we are trying to merge this actively into the trunk. Although the same PR will not be directly merged, we are in the process of offering equivalent functionality. See commit https://github.com/TIBCOSoftware/bw6-plugin-maven/commit/344fc6985db9095feb0571851f9069ef76f8c8f7 for more details.

**Comment by rajani007** [comment]
@awagle Thanks for your quick response. Do you know how long does it take. Currently i am able to compile the plugin code and an achieve whaterver i want in local. Basically looking for a way to create plugin installer.

If you are already in the process. That's cool.

**Comment by awagle** [comment]
Please have a look at the Wiki pages for the Build. https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/Build. Currently we cannot confirm a firm timeline for this but it should be done very soon.

**Comment by awagle** [comment]
This is fixed in a different way. Closing this Pull Request.

**Pull request closed without merging**
